---

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - "errorlint"
        - "dupl"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  depguard:
    list-type: "denylist"
    packages-with-error-message:
      - github.com/stretchr/testify/require: "testing is done using gotest.tools/v3/assert"
      - github.com/stretchr/testify/assert: "testing is done using gotest.tools/v3/assert"
  errcheck:
    check-blank: true
    exclude-functions:
      - "io.ReadAll"
      - "(io.ReadCloser).Close"
      - "encoding/json.Marshal"
      - "encoding/json.MarshalIndent"
  errchkjson:
    check-error-free-encoding: true
    report-no-exported: true
  errorlint:
    errorf: false
  gci:
    custom-order: true
    sections:
      - "standard"
      - "default"
      - "prefix(github.com/krostar/"
      - "dot"
  goconst:
    ignore-tests: true
  gocritic:
    disabled-checks:
      - "ifElseChain"
  godot:
    capital: true
    period: true
    scope: "toplevel"
  gomnd:
    ignored-numbers: ["10", "32", "64", "128"]
  gofumpt:
    extra-rules: true
  govet:
    check-shadowing: true
    disable:
      - "fieldalignment"
    enable-all: true
  grouper:
    import-require-grouping: true
    import-require-single-import: true
  importas:
    alias:
      - pkg: "github.com/google/go-cmp/cmp"
        alias: "gocmp"
      - pkg: "github.com/google/go-cmp/cmp/cmpopts"
        alias: "gocmpopts"
      - pkg: "github.com/krostar/httpclient/test"
        alias: "httpclienttest"
    no-extra-aliases: true
  misspell:
    locale: "US"
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: "atomic"
      - name: "bare-return"
      - name: "blank-imports"
      - name: "bool-literal-in-expr"
      - name: "call-to-gc"
      - name: "constant-logical-expr"
      - name: "context-as-argument"
      - name: "context-keys-type"
      - name: "datarace"
      - name: "deep-exit"
      - name: "defer"
      - name: "defer"
      - name: "defer"
      - name: "dot-imports"
      - name: "duplicated-imports"
      - name: "early-return"
      - name: "empty-block"
      - name: "empty-lines"
      - name: "error-naming"
      - name: "error-return"
      - name: "error-strings"
      - name: "errorf"
      - name: "exported"
      - name: "get-return"
      - name: "identical-branches"
      - name: "if-return"
      - name: "import-shadowing"
      - name: "increment-decrement"
      - name: "indent-error-flow"
      - name: "modifies-parameter"
      - name: "modifies-value-receiver"
      - name: "optimize-operands-order"
      - name: "range"
      - name: "range-val-address"
      - name: "range-val-in-closure"
      - name: "receiver-naming"
      - name: "redefines-builtin-id"
      - name: "string-of-int"
      - name: "struct-tag"
      - name: "superfluous-else"
      - name: "time-equal"
      - name: "time-naming"
      - name: "unconditional-recursion"
      - name: "unexported-naming"
      - name: "unexported-return"
      - name: "unnecessary-stmt"
      - name: "unreachable-code"
      - name: "unused-parameter"
      - name: "unused-receiver"
      - name: "useless-break"
      - name: "var-declaration"
      - name: "var-naming"
      - name: "waitgroup-by-value"
  stylecheck:
    checks: ["all", "-ST1000", "ST1020", "ST1021", "ST1022"]
  tagliatelle:
    case:
      rules:
        json: "snake"
        yaml: "kebab"
  whitespace:
    multi-func: true

linters:
  disable-all: true
  enable:
    - "asciicheck"
    - "bidichk"
    - "containedctx"
    - "contextcheck"
    - "depguard"
    - "dupl"
    - "dupword"
    - "durationcheck"
    - "errcheck"
    - "errchkjson"
    - "errname"
    - "errorlint"
    - "execinquery"
    - "exhaustive"
    - "exportloopref"
    - "gci"
    - "gochecknoglobals"
    - "gochecknoinits"
    - "goconst"
    - "gocritic"
    - "godot"
    - "godox"
    - "gofumpt"
    - "gomnd"
    - "goprintffuncname"
    - "gosec"
    - "gosimple"
    - "govet"
    - "grouper"
    - "importas"
    - "ineffassign"
    - "interfacebloat"
    - "misspell"
    - "nakedret"
    - "nestif"
    - "nilerr"
    - "nilnil"
    - "noctx"
    - "nolintlint"
    - "nonamedreturns"
    - "nosprintfhostport"
    - "predeclared"
    - "revive"
    - "staticcheck"
    - "stylecheck"
    - "tagliatelle"
    - "tenv"
    - "testableexamples"
    - "typecheck"
    - "unconvert"
    - "unparam"
    - "unused"
    - "usestdlibvars"
    - "whitespace"

run:
  skip-dirs:
    - "internal/example"

...
